server:
    port: 8080
    servlet: 
        context-path: /rchat

spring:
    application:
        name: chat_system
    datasource:
        url: ${DB_URL}
        driverClassName: "org.postgresql.Driver"
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    output:
        ansi:
            enabled: ALWAYS
        
logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(%5p) %clr(---){faint} %clr([%t]){cyan} %clr(%-40.40logger{39}){magenta} %clr(:){faint} %m%n%wEx"

jwt:
  signerKey: ${SIGNER_KEY}
  valid-duration: 3600
  refreshable-duration: 36000