server:
    port: 8080
    servlet: 
        context-path: /rchat

spring:
    application:
        name: chat_system
    datasource:
        url: ${DB_URL}
        driverClassName: "org.postgresql.Driver"
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    mail:
        host: "smtp.gmail.com"
        port: 587
        username: ${EMAIL_ACCOUNT}
        password: ${EMAIL_APP_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
    output:
        ansi:
            enabled: ALWAYS
        
logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(%5p) %clr(---){faint} %clr([%t]){cyan} %clr(%-40.40logger{39}){magenta} %clr(:){faint} %m%n%wEx"

jwt:
  signerKey: ${SIGNER_KEY}
  access-token-duration: 3600
  refresh-token-duration: 36000
#   valid-duration: 3600
#   refreshable-duration: 36000